import React, { useEffect } from "react";
import SEO from "../components/seo/SEO";
import { ChevronRight } from "lucide-react";
import { useNavigate } from "react-router-dom";

const sections = [
  {
    id: "interpretation",
    title: "Interpretation and Definitions",
    content: (
      <div className="space-y-6">
        <h3 className="text-2xl font-bold text-[#09090F]">Interpretation</h3>
        <p className="text-gray-700 leading-relaxed text-lg">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>
        <h3 className="text-2xl font-bold text-[#09090F]">Definitions</h3>
        <p className="text-gray-700 leading-relaxed text-lg">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 space-y-3 text-gray-700 text-lg">
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Biosoftech solutions Private limited, First floor, H- Block, Anora Kala, Near Goel Tower, Faizabad road, Lucknow , Uttar Pradesh - 226028</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Website</strong> refers to Biosoftech solutions, accessible from www.biosoftech.com.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Country</strong> refers to: Delhi, India</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        </ul>
      </div>
    ),
  },
  {
    id: "collecting",
    title: "Collecting and Using Your Personal Data",
    content: (
      <div className="space-y-6">
        <h3 className="text-2xl font-bold text-[#09090F]">Types of Data Collected</h3>
        <h4 className="text-xl font-bold text-[#09090F]">Personal Data</h4>
        <p className="text-gray-700 leading-relaxed text-lg">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 space-y-3 text-gray-700 text-lg">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Selfie face image in mobile app</li>
          <li>Usage Data</li>
        </ul>
        <h4 className="text-xl font-bold text-[#09090F]">Usage Data</h4>
        <p className="text-gray-700 leading-relaxed text-lg">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          Usage Data may include information such as your device's IP address, browser type, browser version, pages visited, date and time of visit, time spent on pages, unique device identifiers, and other diagnostic data.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          When accessing the Service through a mobile device, we may collect device type, mobile device ID, IP address, operating system, mobile browser type, and other diagnostic data.
        </p>
      </div>
    ),
  },
  {
    id: "tracking",
    title: "Tracking Technologies and Cookies",
    content: (
      <div className="space-y-6">
        <p className="text-gray-700 leading-relaxed text-lg">
          We use Cookies and similar tracking technologies such as beacons, tags, and scripts to track activity and improve our Service.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          You may refuse cookies through your browser settings, but some parts of the Service may not function properly.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          Cookies can be Persistent (remain after closing browser) or Session-based (deleted when browser is closed).
        </p>
        <h4 className="text-xl font-bold text-[#09090F]">Types of Cookies We Use</h4>
        <ul className="list-disc pl-6 space-y-3 text-gray-700 text-lg">
          <li><strong>Necessary / Essential Cookies:</strong> Enable core functionality such as authentication and fraud prevention.</li>
          <li><strong>Cookies Policy Acceptance:</strong> Identify whether users have accepted cookies usage.</li>
          <li><strong>Functionality Cookies:</strong> Remember user preferences such as login details and language.</li>
          <li><strong>Tracking & Performance Cookies:</strong> Analyze website traffic and user behavior.</li>
          <li><strong>Targeting & Advertising Cookies:</strong> Display advertisements based on browsing behavior and interests.</li>
        </ul>
      </div>
    ),
  },
  {
    id: "use",
    title: "Use of Your Personal Data",
    content: (
      <ul className="list-disc pl-6 space-y-3 text-gray-700 text-lg">
        <li>To provide and maintain the Service and monitor its usage.</li>
        <li>To verify attendance regularization requests using selfie images for HR verification.</li>
        <li>To manage user accounts and provide access to Service features.</li>
        <li>To fulfill contractual obligations for purchased products or services.</li>
        <li>To communicate via email, phone, SMS, or push notifications.</li>
        <li>To send news, offers, and promotional content unless opted out.</li>
        <li>To manage and respond to user requests.</li>
      </ul>
    ),
  },
  {
    id: "sharing",
    title: "Sharing of Personal Information",
    content: (
      <ul className="list-disc pl-6 space-y-3 text-gray-700 text-lg">
        <li>With service providers for analytics, advertising, communication, and payment processing.</li>
        <li>During business transfers such as mergers or acquisitions.</li>
        <li>With affiliates, business partners, and promotional partners.</li>
        <li>With other users if you share information publicly or via third-party social services.</li>
      </ul>
    ),
  },
  {
    id: "retention",
    title: "Retention of Your Personal Data",
    content: (
      <div className="space-y-6">
        <p className="text-gray-700 leading-relaxed text-lg">
          Personal Data is retained only as long as necessary for legal, operational, and business purposes.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          Usage Data is retained for internal analysis and security improvements.
        </p>
      </div>
    ),
  },
  {
    id: "transfer",
    title: "Transfer of Your Personal Data",
    content: (
      <div className="space-y-6">
        <p className="text-gray-700 leading-relaxed text-lg">
          Data may be processed outside your jurisdiction with appropriate security safeguards.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          Your consent indicates agreement to such transfers.
        </p>
      </div>
    ),
  },
  {
    id: "disclosure",
    title: "Disclosure of Your Personal Data",
    content: (
      <ul className="list-disc pl-6 space-y-3 text-gray-700 text-lg">
        <li>Disclosure may occur during business transactions.</li>
        <li>Disclosure may be required by law enforcement or legal obligations.</li>
        <li>Disclosure may be necessary to protect rights, safety, and prevent wrongdoing.</li>
      </ul>
    ),
  },
  {
    id: "security",
    title: "Security of Your Personal Data",
    content: (
      <p className="text-gray-700 leading-relaxed text-lg">
        We use commercially acceptable measures to protect data, but absolute security cannot be guaranteed.
      </p>
    ),
  },
  {
    id: "analytics",
    title: "Analytics & Advertising",
    content: (
      <div className="space-y-6">
        <p className="text-gray-700 leading-relaxed text-lg">
          We use third-party analytics tools such as Clicky.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          Advertising partners may include Bing Ads, Flurry, InMobi, StartApp, AdColony, and AppLovin.
        </p>
      </div>
    ),
  },
  {
    id: "children",
    title: "Children's Privacy",
    content: (
      <div className="space-y-6">
        <p className="text-gray-700 leading-relaxed text-lg">
          The Service does not address users under the age of 13.
        </p>
        <p className="text-gray-700 leading-relaxed text-lg">
          Data collected from minors without parental consent will be removed.
        </p>
      </div>
    ),
  },
  {
    id: "links",
    title: "Links to Other Websites",
    content: (
      <p className="text-gray-700 leading-relaxed text-lg">
        We are not responsible for third-party websites or their privacy practices.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to This Privacy Policy",
    content: (
      <p className="text-gray-700 leading-relaxed text-lg">
        We may update this Privacy Policy and notify users accordingly.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact Us",
    content: (
      <div className="space-y-4 text-gray-700 text-lg">
        <p>Email: <a href="mailto:sales@biosoftech.com" className="text-[#3793DB] hover:underline">sales@biosoftech.com</a></p>
        <p>Website: <a href="https://www.biosoftech.com" target="_blank" rel="noreferrer" className="text-[#3793DB] hover:underline">www.biosoftech.com</a></p>
      </div>
    ),
  },
];

export default function PrivacyPolicy() {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-white pt-20 sm:pt-24 md:pt-28">
      <SEO
        title="Privacy Policy – Biosoftech Solutions"
        description="Read the Privacy Policy of Biosoftech Solutions to understand how we collect, use, and protect your personal information."
        keywords="privacy policy, data privacy, Biosoftech, information security"
        ogUrl="https://www.biosoftech.com/privacy-policy"
      />

      {/* Hero Header */}
      <section className="bg-[#f8faff] py-16 md:py-24 border-b border-gray-100">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-sm text-gray-500 mb-4">Last Updated: December 01, 2025</p>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-[#09090F] mb-6">
            Privacy Policy
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 max-w-4xl mx-auto leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="text-lg sm:text-xl text-gray-600 max-w-4xl mx-auto leading-relaxed mt-4">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>
        </div>
      </section>

      {/* Main Content Area */}
      <section className="py-16 md:py-24">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row gap-12 lg:gap-20">

            {/* Sidebar */}
            <aside className="lg:w-1/4 lg:sticky lg:top-32 h-fit space-y-10">
              <div>
                <h3 className="text-2xl font-bold text-[#09090F] uppercase tracking-wider mb-6">
                  Biosoftech
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  Biosoftech Solutions is committed to protecting your privacy and ensuring transparency in how we handle your data.
                </p>
              </div>

              <div className="border-t border-gray-100 pt-8">
                <h4 className="text-xl font-bold text-[#09090F] uppercase tracking-wider mb-6">
                  Useful Topics
                </h4>
                <nav className="flex flex-col space-y-4">
                  {sections.map((section) => (
                    <a
                      key={section.id}
                      href={`#${section.id}`}
                      className="text-[#3793DB] font-semibold hover:text-[#2c76af] transition-colors text-base inline-flex items-center gap-2"
                    >
                      <ChevronRight size={14} />
                      {section.title}
                    </a>
                  ))}
                </nav>
              </div>
            </aside>

            {/* Content */}
            <div className="lg:w-3/4 space-y-20">
              {sections.map((section) => (
                <div key={section.id} id={section.id} className="scroll-mt-32">
                  <h2 className="text-3xl sm:text-4xl font-bold text-[#3793DB] mb-8">
                    {section.title}
                  </h2>
                  <div className="content">
                    {section.content}
                  </div>
                </div>
              ))}

              <div className="pt-12 border-t border-gray-100">
                <div className="flex items-center justify-between flex-wrap gap-4">
                  <p className="text-gray-600 text-lg">
                    Go Back To Home
                  </p>
                  <button
                    onClick={() => navigate("/")}
                    className="inline-flex items-center gap-2 bg-[#3793DB] hover:bg-[#2c76af] text-white px-10 py-4 rounded-full font-bold text-lg transition-all duration-300 shadow-lg shadow-blue-100"
                  >
                    Home <ChevronRight size={20} />
                  </button>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
    </div>
  );
}
